### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by Prologh** [mcserep/NetOctree#1]
Hi!
Looks like a great library. Sadly, I couldn't find it on NuGet. Is there any change or plans to upload to make available via NuGet?
Regards

**Comment by mcserep** [comment]
Hello!
I have uploaded it to NuGet: https://www.nuget.org/packages/NetOctree/

**Comment by Prologh** [comment]
Great! Thanks!

**Comment by petrasvestartas** [comment]
Is it possible to make it work for .NET framework 4.5.2 ?
```

Install-Package : Could not install package 'NetOctree 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that 
framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package NetOctree -Version 1.0.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
```

**Comment by mcserep** [comment]
> Is it possible to make it work for .NET framework 4.5.2 ?
>

The codebase itself if .NET Framework 4.5.2 compliant, so I have also targeted it, it shall work with the 1.0.1 version:
https://www.nuget.org/packages/NetOctree/1.0.1

However, I would recommend to update the .NET Framework version used in your project if possible.
Please comment if you have any further questions.
