### ISSUE TITLE
BoundingOctree not intersecting right boxes

### ISSUE THREAD

**Issue by tsukasa1989** [mcserep/NetOctree#10]
I am using the BoundingOctree for mesh intersection to find the correct faces. We internally now use a Vertex class and we have to convert it to Vector3.

Filling my Octree:

        internal void BuildFaceOctree()
        {
            var bb = new Box3(Vertices.ToArray());
            var bbcenter = bb.Center();

            var tree = new BoundsOctree<Face>(1, new Vector3((float)bbcenter.X, (float)bbcenter.Y, (float)bbcenter.Z), 1, 1.25f);
            for (var i =0;i< _faces.Count;i++)
            {
                var f = _faces[i];
                var max = Vertex.Max(Vertex.Max(Vertices[f.A], Vertices[f.B]), Vertices[f.C]);
                var min = Vertex.Min(Vertex.Min(Vertices[f.A], Vertices[f.B]), Vertices[f.C]);
                var center = (min + max) / 2;
                var grow = max - min + new Normal(5, 5, 5);

                var octbb = new Octree.BoundingBox(new Vector3((float)center.X, (float)center.Y, (float)center.Z), new Vector3((float)grow.X, (float)grow.Y, (float)grow.Z));
                tree.Add(f, octbb);
            }
            _faceOctree = tree;
        }

And the ray with RayLength:

        var intersectingFaces = mesh.FaceOctree.GetColliding(ray, rayLength);

I have 3 double checked the bounding boxes, I even added a size of 5 into all directions to not have issues with faces that are flat and don't have any Height for example. 

My simple test of a Box (Cube) of -50,-50,-50 to 50,50,50 and a simple intersection from origin (5, 0, 0) in direction (0, 0, -1) with length 100 is not even hitting the right faces. It is resulting in 2 wrong faces.

Any suggestions?

**Comment by mcserep** [comment]
Hi @tsukasa1989 ,
Do you still have any active questions - as I see you have closed the issue?

**Comment by tsukasa1989** [comment]
It was not in the Octree, I had an issue somewhere else. So it was resolved.

Thank you.
