### ISSUE TITLE
Octree and Pointclouds

### ISSUE THREAD

**Issue by petrasvestartas** [mcserep/NetOctree#3]
Hi,

I would like to ask if there is any interesent in extending this project for pointclouds?

I am trying to find implementations for 2d case, how to create outlines of sectioned 2d pointlist that is a section of a building.

What I would like to  do is to draw polygon from a list of points 
![A-2D-slice-of-the-octree-splitting-volume-The-resolution-is-high-around-the-surface-and-1](https://user-images.githubusercontent.com/18013985/93000206-0edb3c80-f527-11ea-8282-d95dbc38764e.png)

**Comment by mcserep** [comment]
There are 2 spatial index types in the library: `BoundsOctree<T>` and `PointOctree<T>`. The `PointOctree<T>` can be used to index simple 3D points.
