### ISSUE TITLE
Provide a thread-safe implementation of the octree

### ISSUE THREAD

**Issue by lschiemann** [mcserep/NetOctree#6]
Thanks for your lib.
We use your implementation in a multi-threaded app. Unfortunately the octree is not thread-safe. So we are forced to create an octree per thread. This is not very memory friendly. Can you provide a thread-safe implementation? And if not, what should we consider if we want to make an own thread-safe implementation?

Kind Regards...

**Comment by mcserep** [comment]
Hi @lschiemann,
I am glad you found the library useful. As for the thread-safe implementation, I see 2 possible approaches: both have benefits, but also disadvantages.

1. You may easily add a mutual exclusion locking mechanism to the public methods of the `PointOctree` and `BoundsOctree` classes, making them thread-safe. You may also add a separate "write-lock" and "read-lock", so multiple read operations can be performed in parallel. While it is easy to implement, I am not sure how much would this decrease the performance of the octree, especially if there both write and read operations are executed simultaneously. (A proper priority queueing should guarantee that there will be no starvation will for either the read operations or the write operations.)

2. A finer grained approach is to handle the locking not on the tree, but on the nodes themselves: go down the tree, figure out where the node needs to be added, which parent nodes it will affect, wait for a lock on those, lock them, do the add operation and unlock. This will always keep the tree in a consistent state while allowing concurrent add operations in different parts of the tree. (Same for removal of nodes.) On the other hand it is much more complex to implement properly, more locks are required (1 per each node), which will effect both the memory and the computational footprint of your program.

**Comment by mcserep** [comment]
I will close this now, but in case you submit a PR, I would be glad to review it.
